// Application Constants
export const APP_CONSTANTS = {
  // Pagination
  DEFAULT_PAGE_SIZE: 20,
  MAX_PAGE_SIZE: 100,
  DEFAULT_ORDER_PAGE_SIZE: 10,
  
  // Password & Security
  BCRYPT_SALT_ROUNDS: 12,
  ENCRYPTION_ALGORITHM: 'aes-256-gcm',
  
  // JWT Token Types
  JWT_TOKEN_TYPES: {
    ACCESS: 'access',
    REFRESH: 'refresh'
  } as const,
  
  // Default JWT Expiry
  DEFAULT_JWT_ACCESS_EXPIRES_IN: '15m',
  DEFAULT_JWT_REFRESH_EXPIRES_IN: '7d',
  
  // Currency
  CURRENCY: {
    CODE: 'INR',
    SYMBOL: '₹'
  } as const,
  
  // Error Codes
  ERROR_CODES: {
    // Authentication
    INVALID_CREDENTIALS: 'INVALID_CREDENTIALS',
    USER_EXISTS: 'USER_EXISTS',
    USER_NOT_FOUND: 'USER_NOT_FOUND',
    ACCOUNT_SUSPENDED: 'ACCOUNT_SUSPENDED',
    MISSING_TOKEN: 'MISSING_TOKEN',
    INVALID_TOKEN: 'INVALID_TOKEN',
    INVALID_TOKEN_TYPE: 'INVALID_TOKEN_TYPE',
    INVALID_REFRESH_TOKEN: 'INVALID_REFRESH_TOKEN',
    
    // Validation
    VALIDATION_ERROR: 'VALIDATION_ERROR',
    INVALID_AMOUNT: 'INVALID_AMOUNT',
    INVALID_QUANTITY: 'INVALID_QUANTITY',
    
    // Business Logic
    INSUFFICIENT_BALANCE: 'INSUFFICIENT_BALANCE',
    INSUFFICIENT_STOCK: 'INSUFFICIENT_STOCK',
    EMPTY_CART: 'EMPTY_CART',
    CART_NOT_FOUND: 'CART_NOT_FOUND',
    VARIANT_NOT_FOUND: 'VARIANT_NOT_FOUND',
    VARIANT_INACTIVE: 'VARIANT_INACTIVE',
    ORDER_NOT_FOUND: 'ORDER_NOT_FOUND',
    CANNOT_CANCEL: 'CANNOT_CANCEL',
    ACCESS_DENIED: 'ACCESS_DENIED',
    
    // System
    TOPUP_FAILED: 'TOPUP_FAILED',
    INTERNAL_ERROR: 'INTERNAL_ERROR'
  } as const,
  
  // HTTP Status Codes
  HTTP_STATUS: {
    OK: 200,
    CREATED: 201,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500
  } as const,
  
  // Validation Rules
  VALIDATION_RULES: {
    PASSWORD_MIN_LENGTH: 8,
    PASSWORD_MAX_LENGTH: 128,
    EMAIL_MAX_LENGTH: 255,
    NAME_MAX_LENGTH: 100,
    PHONE_LENGTH: 10,
    DESCRIPTION_MAX_LENGTH: 500
  } as const
};

// Type exports for better type safety
export type ErrorCode = typeof APP_CONSTANTS.ERROR_CODES[keyof typeof APP_CONSTANTS.ERROR_CODES]; 